Brang corrections of Alert component documentation
gravity-ui/uikit pull request #1017
Opened 2023-09-18 13:20 UTC by vvtimofeev

Brang corrections to English, introduced in https://st.yandex-team.ru/CLOUDLOC-927

2023-09-18 14:24 UTC, amje requested changes

2023-09-18 14:24 UTC, amje commented on src/components/Alert/README.md
> +`vertical` - used to direct users to content if there are property `actions` with buttons. For showing buttons below text (
Changing `is` to `are` seems a mistake

2023-09-18 14:24 UTC, amje commented on src/components/Alert/README.md
> +`horizontal` - used to direct users to content if there are property `actions` with buttons. For showing buttons to the right
Same here

2023-09-18 14:41 UTC, vvtimofeev commented on src/components/Alert/README.md
> +`vertical` - used to direct users to content if there are property `actions` with buttons. For showing buttons below text (
ok

2023-09-18 14:46 UTC, amje approved these changes

2023-09-21 10:25 UTC, IsaevAlexandr approved these changes

2023-09-21 11:32 UTC, imsitnikov approved these changes

2023-09-21 15:14 UTC, merged