fix(Table): fixed not working sorting when controlled sortState is used
gravity-ui/uikit pull request #1032
Opened 2023-10-02 07:14 UTC by zzzorgo

The method `isControlledState()` in this HOC is for determining whether the `sortState` is provided externally or not. It shouldn't turn off the whole sorting as it does in this case making the whole HOC useless.

2023-10-02 13:28 UTC, ValeraS requested changes

2023-10-02 13:28 UTC, ValeraS commented on src/components/Table/hoc/withTableSorting/withTableSorting.tsx
> +            if (sortState.length === 0) {
It's breaking change. I think it's better add prop that controls a use of inner/external sorting,  and `onSortStateChange` should be always called, not only in controlled state.

```ts
const {useExternalSortings = this.isControlledState()} = this.props
if (useExternalSorting || sortState.length === 0) {
```

2023-10-02 14:39 UTC, zzzorgo commented
@ValeraS Pushed the change in accord with your comment

2023-10-03 16:13 UTC, ValeraS requested changes

2023-10-03 16:13 UTC, ValeraS commented on src/components/Table/hoc/withTableSorting/withTableSorting.tsx
> +    useExternalSorting?: boolean;
Let's rename to
```suggestion
    disableDataSorting?: boolean;
```

2023-10-04 13:19 UTC, ValeraS approved these changes

2023-10-04 13:24 UTC, merged