feat: synced codeowners with sharepoint table
gravity-ui/uikit pull request #1034
Opened 2023-10-02 13:29 UTC by vvtimofeev

Synced codeowners file with [sharepoint table](https://yandexteam.sharepoint.com/:x:/r/sites/wiki-ms2/Shared%20Documents/wiki_pages/users/timofeyevvv/[gravityui-mainteiners.xlsx](https://yandexteam.sharepoint.com/:x:/r/sites/wiki-ms2/Shared%20Documents/wiki_pages/users/timofeyevvv/gravityui-mainteiners.xlsx?d=wcf62d1ca43f9497081240e78967c4511&csf=1&web=1&e=qz9oBT)?d=wcf62d1ca43f9497081240e78967c4511&csf=1&web=1&e=qz9oBT)

2023-10-02 14:38 UTC, korvin89 approved these changes

2023-10-02 18:45 UTC, amje requested changes

2023-10-02 18:45 UTC, amje commented on CODEOWNERS
> +/src/components/Pagination @jhoncool
duplicated line

2023-10-03 06:13 UTC, vvtimofeev commented on CODEOWNERS
> +/src/components/Pagination @jhoncool
Thank you! I deleted it.

2023-10-03 12:16 UTC, amje approved these changes

2023-10-03 12:16 UTC, merged