feat: new list proposal
gravity-ui/uikit pull request #1090
Opened 2023-11-03 12:27 UTC by IsaevAlexandr

Completely rewritten to version with hooks.

Prev pr: https://github.com/gravity-ui/uikit/pull/1039

2023-11-20 13:39 UTC, Mishnya commented
I see you're using the `react-window`.

This library has a problem. In rtl, the list for an item when dragging sets the style `right: 0` instead `right: undefined`, which causes the item to move to the right until the end of the screen.

To fix this you can manually set `right: undefined` to the item. I didn't find any more problems with with this bug and fix but maybe we can find an alternative to this library (which has not been updated since December 2018).

2024-01-11 17:11 UTC, amje requested changes

2024-01-11 17:11 UTC, amje commented on src/components/useList/components/ListContainerView/ListContainerView.tsx
> +export interface ListContainerViewProps extends QAProps, React.HTMLAttributes<'div'> {
Let's apply rest props via separate prop, `extraProps`. The component should alse allow to override `div` element

2024-01-11 17:11 UTC, amje commented on src/components/useList/components/ListContainerView/ListContainerView.scss
> +        height: var(--g-list-height, 300px);
Let's not mix stable and unstable feautures together, `--g-list-height` probably will be a part of CSS for old List

2024-01-16 15:56 UTC, IsaevAlexandr commented on src/components/useList/hooks/useListFilter.ts
> +    const filterRef = React.useRef<HTMLInputElement>(null);
for two reasons:
- over time, logic may appear where access is needed access to DOM element;
- it is convenient to have a ready-made ref to use right in the hook

2024-01-16 16:42 UTC, IsaevAlexandr commented on src/components/useList/components/ListItemView/ListItemView.tsx
> +                    {startSlot ??
to override this behaviour. If you need both icons pass component in slot like:
```tsx
startSlot={
   <>
      <Icon />
      <Icon data={Check} size={16} className={colorText({color: 'info'})} />
  </>
}
```

2024-01-16 16:47 UTC, IsaevAlexandr commented on src/components/useList/components/ListItemView/ListItemView.scss
> +            width: 16px;
it's a component with fixed width corresponding to space if list has nested structure

2024-01-18 12:14 UTC, amje requested changes

2024-01-18 12:14 UTC, amje commented on src/components/useList/components/ListItemView/ListItemView.scss
> +        border-radius: var(--g-list-item-border-radius-xl, 8px);
public var should be without any size, just `--g-list-item-border-radius`

2024-01-18 12:14 UTC, amje commented on src/components/useList/types.ts
> +export type ListItemSizeType = 's' | 'm' | 'l' | 'xl';
`ListItemSize`, "Type" suffix is redundant

2024-01-18 12:14 UTC, amje commented on src/unstable.ts
>  export * from './components/TreeSelect';
We keep TreeSelect stable?

2024-01-18 12:20 UTC, amje requested changes

2024-01-18 12:20 UTC, amje commented on src/components/useList/components/ListItemView/ListItemView.tsx
> +            role = 'listitem',
role `option` more suitable here, it supports `aria-selected` attribute, while `listitem` doesn't

2024-01-18 13:49 UTC, IsaevAlexandr commented
/fixed

2024-01-19 15:25 UTC, korvin89 approved these changes

2024-01-22 14:23 UTC, IsaevAlexandr commented on src/components/useList/hooks/useListFilter.ts
> +    }
it's new recommended way to not use `useEffect` things in code - https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes

2024-01-22 14:38 UTC, merged

2024-01-22 15:55 UTC, GermanVor commented on src/components/useList/hooks/useListFilter.ts
> +    }
Interesting. Why they do not use `React.useRef` for prev state