feat(Skeleton): support RTL
gravity-ui/uikit pull request #1136
Opened 2023-11-17 11:48 UTC by Mishnya

2023-11-17 17:47 UTC, amje requested changes

2023-11-17 17:47 UTC, amje commented on src/components/Skeleton/Skeleton.scss
> +@keyframes #{variables.$ns}skeleton-rtl {
We can use only one animation and use CSS-vars instead:

```scss

.skeleton {
    --_--from: -100%;
    --_--to: 100%;
    
    [dir='rtl'] & {
        --_--from: 100%;
        --_--to: -100%;
    }
}

@keyframes #{variables.$ns}skeleton {
    0% {
        transform: translateX(var(--_--from));
    }
    100% {
        transform: translateX(var(--_--to));
    }
}

2023-11-21 11:34 UTC, amje requested changes

2023-11-21 11:34 UTC, amje commented on src/components/Skeleton/Skeleton.scss
> +    --g-skeleton-animation-from: -100%;
`--g-*` variables are considerd public form v6 version. Please use "private" syntax: `--_--animation-from`, `...`

2023-11-27 15:18 UTC, amje approved these changes

2023-11-27 15:18 UTC, amje commented
@SeqviriouM Check please

2023-11-28 08:22 UTC, SeqviriouM approved these changes

2023-11-28 08:24 UTC, merged