test(PlaywrightNewScreenshot): added the expectScreenshot fixture
gravity-ui/uikit pull request #1192
Opened 2023-12-08 11:02 UTC by NasgulNexus

added the expectScreenshot fixture, which makes it possible to take screenshots in light and dark themes

2023-12-11 13:12 UTC, amje commented
There are double dashes in snapshot names

2023-12-11 14:00 UTC, NasgulNexus commented
> @NasgulNexus There are double dashes in snapshot names

fixed the double dash

2023-12-22 13:53 UTC, amje requested changes

2023-12-22 13:53 UTC, amje commented on playwright/README.md
> +Take a screenshot by default, takes a screenshot in a light theme
```suggestion
Capture a screenshot, by default in light theme only:
```

2023-12-22 13:53 UTC, amje commented on playwright/README.md
> +import {MyTestedComponent} from '../MyTestedComponent';
Just `Component` would be ok, `Tested` means it's tested?

2023-12-22 13:53 UTC, amje commented on playwright/README.md
> +test('Name test', async ({mount}) => {
```suggestion
test('test description', async ({mount}) => {
```

2023-12-22 13:53 UTC, amje commented on playwright/README.md
> +  //mounting a component
```suggestion
  // mount the component
```

2023-12-22 13:53 UTC, amje commented on playwright/README.md
> +  //screenshot
```suggestion
  // capture the screenshot
```

2023-12-22 13:53 UTC, amje commented on playwright/README.md
> +You can also take screenshots in dark and light themes
```suggestion
You can also capture screenshots both in dark and light themes:
```

2023-12-22 13:53 UTC, amje commented on playwright/README.md
> +or if you need to do any actions on the component
```suggestion
If you need to do any actions with the component:
```

2023-12-22 13:53 UTC, amje commented on playwright/core/expectScreenshotFixture.ts
> +        expect(await captureScreenshot('g-root_theme_light')).toMatchSnapshot({
Better to pass `light` or `dark`, and use it inside `captureScreenshot` like so: `g-root_theme_${theme}`

2023-12-25 11:28 UTC, amje approved these changes

2023-12-25 15:35 UTC, korvin89 approved these changes

2023-12-25 15:40 UTC, merged