feat: add scroll controll prop to define scroll position
gravity-ui/uikit pull request #1211
Opened 2023-12-20 09:02 UTC by DenisVershkov

2023-12-20 10:10 UTC, DenisVershkov commented
[DATAUI-1254]

2023-12-20 10:55 UTC, korvin89 commented
Could u provide some description?

2023-12-20 13:15 UTC, DenisVershkov commented
1) Added prop 'scroll' to the Modal and Dialog. The prop handles scroll appearance:  
- if 'inner' is selected, then scroll will be applied to the DialogBody
- if 'outer' is selected, then scroll will appear outside (the same behaviour as before)
- 'outer' is the default value

2) Added prop 'withDivider' to the DialogBody component. When this prop has 'true' value, then the DialogBody itself will have top and bottom border. This is made for the 'inner' scroll case and should be used something like: <DialogBody withDivider={scroll === 'inner'}>

2023-12-22 14:37 UTC, amje requested changes

2023-12-22 14:37 UTC, amje commented on src/components/Dialog/Dialog.tsx
> +    scroll?: 'inner' | 'outer';
I suggest this naming instead: `contentOverflow?: 'visible' | 'auto'`, symmetrical to the CSS overflow property

2023-12-22 14:37 UTC, amje commented on src/components/Modal/Modal.scss
> +    --yc-modal-with-inner-scroll-margin: 24px;
From v6 we introduce public CSS API, this looks like a private. Please use SCSS var or name it like `--_--inner-scroll-margin` on component's root, not `:root`

2023-12-26 13:57 UTC, amje requested changes

2023-12-26 13:57 UTC, amje commented on src/components/Dialog/Dialog.scss
> +        flex-direction: column;
Let's make container always flex, not with this mod only

2024-01-16 09:20 UTC, amje requested changes

2024-01-16 09:20 UTC, amje commented on src/components/Modal/Modal.tsx
> +                        <div className={b('content-container')}>
Let's call them `content-aligner` and `content-wrapper`

2024-01-16 09:20 UTC, amje commented on src/components/Dialog/DialogBody/DialogBody.tsx
> +    const {className, withDividers = false} = props;
We use `has*` naming throughout the codebase (i.e. `hasClear`, `hasClose`, `hasArrow`)

2024-01-16 09:20 UTC, amje commented on src/components/Dialog/Dialog.scss
> +        max-height: calc(100vh - var(--yc-modal-margin) * 2);
Let's use SCSS var instead, this var will be removed in v6

2024-01-17 14:48 UTC, DenisVershkov commented
in order not to deal with merge conflicts, i created a new one #1251

2024-01-17 14:48 UTC, DenisVershkov commented
in order not deal with merge conflicts, i created a new one #1251

2024-01-17 14:48 UTC, closed without merging