feat(Dialog): add prop contentOverflow to control overflow behaviour
gravity-ui/uikit pull request #1251
Opened 2024-01-17 14:45 UTC by DenisVershkov

1. Added prop 'contentOverflow' to the Modal and Dialog. The prop handles scroll appearance:

- if 'auto' is selected, then scroll will be applied to the DialogBody
- if 'visible' is selected, then scroll will appear outside (the same behaviour as before)
- 'visible' is the default value

2. Added prop 'hasDivider' to the DialogBody component. When this prop value is 'true', then DialogBody has top and bottom border. I've done this for the contentOverflow 'auto' case, so it should be used like: <DialogBody hasDivider={contentOverflow === 'auto'}>

2024-01-17 16:52 UTC, amje requested changes

2024-01-17 16:52 UTC, amje commented on src/components/Dialog/Dialog.scss
> +            100vh - calc(var(--g-modal-margin, #{variables.$modal-default-margin})) * 2
2nd calc is just wraps var?

2024-01-17 16:52 UTC, amje commented on src/components/Dialog/DialogBody/DialogBody.tsx
> +    hasDividers?: boolean;
Wouldn't be `hasBorders` more precise? Divider - smth that splits the content, border - is on the edge. While it's a `DialogBody` prop, borders suits better imo.

2024-01-17 16:52 UTC, amje commented on src/components/Modal/Modal.scss
> +                100vh - calc(var(--g-modal-margin, #{variables.$modal-default-margin})) * 2
Same comment as above

2024-01-17 16:52 UTC, amje commented on src/components/variables.scss
> +$modal-default-border-radius: 5px;
While we're only using it inside the Modal, we don't need to share it.

2024-01-18 11:40 UTC, amje approved these changes

2024-01-18 13:51 UTC, merged

2024-01-18 13:51 UTC, DenisVershkov commented
closes [DATAUI-1254]