feat: outline for text input and select
gravity-ui/uikit pull request #1318
Opened 2024-02-07 15:40 UTC by Kyzyl-ool

2024-02-07 16:27 UTC, amje commented on src/components/controls/TextArea/README.md
> +| `--g-text-area-outline-color-focus` | Outline color if focused |
`--g-text-area-focus-outline-color`

2024-02-07 16:28 UTC, amje commented on src/components/controls/TextInput/README.md
> +| `--g-text-input-outline-color-focus` | Outline color if focused |
`--g-text-input-focus-outline-color`

2024-02-07 16:29 UTC, amje commented
@Kyzyl-ool Currently I see no difference, is it a bug?

2024-02-08 09:01 UTC, Kyzyl-ool commented
> @Kyzyl-ool Currently I see no difference, is it a bug or there is no default?

I left outline color empty by default, so yes – there shouldn't be any differences. Outline on focus for inputs and selects are debatable

2024-03-04 14:18 UTC, Kyzyl-ool commented
@amje , I would like to propose using error state's color for outline color when error state is on. Just added to the previous commit: https://github.com/gravity-ui/uikit/pull/1318/commits/48f762cdc16bf357d7006738e986763a1d96cfdd

2024-03-12 11:47 UTC, amje requested changes

2024-03-12 11:47 UTC, amje commented on src/components/Select/components/SelectControl/SelectControl.scss
> +            --g-select-focus-outline-color: var(--g-color-line-danger);
This wont allow override this variable, we must use private/public pair here

2024-03-12 11:47 UTC, amje commented on src/components/controls/TextArea/TextArea.scss
> +                        --g-text-area-focus-outline-color: var(--g-color-line-danger);
Same as above

2024-03-12 11:47 UTC, amje commented on src/components/controls/TextInput/TextInput.scss
> +                        --g-text-input-focus-outline-color: var(--g-color-line-danger);
Same as above

2024-03-21 11:01 UTC, amje approved these changes

2024-03-21 14:07 UTC, korvin89 approved these changes

2024-03-21 14:20 UTC, merged