feat(Divider): add the Divider component
gravity-ui/uikit pull request #1322
Opened 2024-02-07 20:53 UTC by v4dyar4

Ticket: UXRFC-265

2024-03-11 22:33 UTC, ValeraS requested changes

2024-03-11 22:33 UTC, ValeraS commented on src/components/Divider/__stories__/Divider.stories.tsx
> +} as Meta;
```suggestion
const meta = Meta<typeof Divider> {
    title: 'Components/Utils/Divider',
    component: Divider,
};

export default meta;
```

2024-03-26 21:34 UTC, v4dyar4 commented on src/components/Divider/Divider.scss
> +    height: auto;
I checked components of the ui-kit, and I did not find one that component would affects on Divider. Removed unnecessary css rules

2024-03-28 10:33 UTC, ValeraS requested changes

2024-03-28 10:33 UTC, ValeraS commented on src/components/Divider/Divider.scss
> +            border-inline-start: 1px solid var(--g-color-line-generic);
Let's add css api like this:
```suggestion
            border-inline-start: 1px solid var(--g-divider-color, var(--g-color-line-generic));
```

and add info about it to readme. https://github.com/gravity-ui/uikit/tree/main/src/components/Button#css-api

2024-03-28 10:33 UTC, ValeraS commented on src/components/Divider/Divider.tsx
> +            aria-orientation={orientation}
I suggest not setting `aria-orientation="horizontal"` because that is the default value for the role separator.

2024-03-28 14:06 UTC, ValeraS approved these changes

2024-03-28 14:49 UTC, merged