RenderItem property of BreadCrumbs
gravity-ui/uikit pull request #1413
Opened 2024-03-08 20:11 UTC by GermanVor

https://github.com/gravity-ui/uikit/issues/1287

2024-03-13 17:07 UTC, korvin89 requested changes

2024-03-13 17:20 UTC, GermanVor commented on src/components/Breadcrumbs/BreadcrumbsItem.tsx
> +        return renderItem({item, children, isCurrent, isPrevCurrent});
Why it is breaking changes ?

There is no exports for this Item  and if user imported it like this - `@gravity-ui/uikit/build/cjs/components/Breadcrumbs/BreadcrumbsItem` - Ts and eslint will inform that prev `renderItem` is not the same as new one.

2024-03-13 17:56 UTC, GermanVor commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +export type RenderItemContent<T extends BreadcrumbsItem> = (
0137809f0a74902c20e0aba833c52e10e7cdd5a6

2024-03-13 17:56 UTC, GermanVor commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +export type RenderItem<T extends BreadcrumbsItem> = (props: RenderItemProps<T>) => React.ReactNode;
0137809f0a74902c20e0aba833c52e10e7cdd5a6

2024-03-13 17:56 UTC, GermanVor commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +export type RenderItemProps<T extends BreadcrumbsItem = BreadcrumbsItem> = {
0137809f0a74902c20e0aba833c52e10e7cdd5a6

2024-03-14 11:33 UTC, korvin89 approved these changes

2024-03-14 13:05 UTC, merged