test(Button): add different more icon tests and different sizes for test
gravity-ui/uikit pull request #1455
Opened 2024-03-26 19:11 UTC by teleginzhenya

2024-03-27 09:16 UTC, amje requested changes

2024-03-27 20:37 UTC, teleginzhenya commented on src/components/Button/__tests__/Button.visual.test.tsx
> +
I've tried to add this in test, however Icon didn't showed (didn't find solution yet), maybe @NasgulNexus can take a look

```jsx
  <Button {...args}>
    <IconComponent size={20} data={Globe} />
    Both bigger icons
    <IconComponent size={20} data={ChevronDown} />
</Button>
```

However I've added `isTest` property to show extra items in Story for test purposes (https://github.com/gravity-ui/uikit/pull/1455/commits/95bb517b270db290b57e9fa89515b161aa482b6b) ([doc](https://storybook.js.org/docs/essentials/controls#fully-custom-args)).

We might discuss later what is the right way for tests. Personally I don't like different markup for tests/stories in different files.

2024-03-27 21:28 UTC, teleginzhenya commented on src/components/Button/__tests__/Button.visual.test.tsx
> +
upd: problem here https://github.com/microsoft/playwright/issues/29854

2024-03-28 14:09 UTC, amje approved these changes

2024-03-28 16:11 UTC, merged