fix(TextInput): turn off event onBlur on input when use clear button
gravity-ui/uikit pull request #1458
Opened 2024-03-28 14:13 UTC by ananas7

2024-03-28 15:50 UTC, korvin89 requested changes

2024-03-28 15:50 UTC, korvin89 commented on src/components/Button/Button.tsx
> +    onMouseUp?: React.MouseEventHandler<HTMLButtonElement | HTMLAnchorElement>;
Lets use [extraProps](https://github.com/gravity-ui/uikit/blob/main/src/components/Button/Button.tsx#L73) instead

2024-03-29 08:04 UTC, ananas7 commented on src/components/Button/Button.tsx
> +    onMouseUp?: React.MouseEventHandler<HTMLButtonElement | HTMLAnchorElement>;
a9c43223c53507efbb8678e2ab14bb8503e16c31

2024-03-29 10:03 UTC, korvin89 approved these changes

2024-03-29 11:08 UTC, merged