fix(withTableSettings): renderClone for dnd
gravity-ui/uikit pull request #1463
Opened 2024-03-29 12:53 UTC by GermanVor

2024-04-01 14:55 UTC, IsaevAlexandr requested changes

2024-04-01 15:11 UTC, IsaevAlexandr commented on src/components/Table/hoc/withTableSettings/TableColumnSetup/TableColumnSetup.tsx
> -                            dragging={snapshot.isDragging}
How was it here

2024-04-01 17:04 UTC, GermanVor commented on src/components/Table/hoc/withTableSettings/TableColumnSetup/TableColumnSetup.tsx
> +                active={snapshot.isDragging}
https://github.com/gravity-ui/uikit/pull/1463/commits/4701c3b2127475536977e4eaf885d6b23f54f840

2024-04-02 15:45 UTC, IsaevAlexandr approved these changes

2024-04-02 15:55 UTC, korvin89 approved these changes

2024-04-04 09:32 UTC, Raubzeug approved these changes

2024-04-05 19:16 UTC, merged