feat: readme update
gravity-ui/uikit pull request #1523
Opened 2024-04-18 12:49 UTC by vvtimofeev

Updated readme file: added UIKit picture in the beginning, some links to our resources, slightly reformulated UIKit description phrase.

2024-04-18 14:33 UTC, amje requested changes

2024-04-18 14:33 UTC, amje commented on docs/assets/logo.svg
Seems not used

2024-04-18 14:57 UTC, korvin89 requested changes
I suppose we should wait for this feature https://github.com/gravity-ui/landing/issues/200 to have opportunity to hide this content in landing page

2024-05-14 13:19 UTC, vvtimofeev commented
> I suppose we should wait for this feature [gravity-ui/landing#200](https://github.com/gravity-ui/landing/issues/200) to have opportunity to hide this content in landing page

I added special markdown block <GITHUB_BLOCK>, it should hide the image and the resources block from the landing. If you don't mind, please reconsider your comment.

2024-05-15 16:20 UTC, korvin89 approved these changes

2024-05-15 16:24 UTC, korvin89 commented
I suppose that icons will be poorly distinguishable in a dark theme

2024-05-16 17:51 UTC, amje approved these changes

2024-05-17 09:57 UTC, merged