feat: add PinInput component
gravity-ui/uikit pull request #1557
Opened 2024-05-01 17:30 UTC by amje

2024-06-10 17:01 UTC, korvin89 requested changes

2024-06-10 18:10 UTC, amje commented on src/components/PinInput/README.md
> +| style            | HTML `style` attribute                                                                                                                               |    `React.CSSProperties`
Root node is by default. Where prop is affecting input and not root node, I explicitly noted it

2024-06-10 18:11 UTC, amje commented on src/components/PinInput/PinInput.tsx
> +            if (onUpdateComplete && newValue.every((v) => Boolean(v))) {
There can be only strings, `Boolean('0') === true`

2024-06-10 18:14 UTC, amje commented on src/components/PinInput/PinInput.tsx
> +                    <div key={i} className={b('item')}>
Nope, TextInput itself has `width: 100%` style which break flex layout

2024-06-10 18:15 UTC, amje commented on src/components/PinInput/PinInput.tsx
> +                            controlRef={handleRef.bind(null, i)}
Yes. I only need curry the index

2024-06-11 08:01 UTC, korvin89 approved these changes

2024-06-11 10:41 UTC, merged