refactor(Slider): migrate CSF3
gravity-ui/uikit pull request #1614
Opened 2024-05-23 14:49 UTC by itwillwork

2024-06-03 09:10 UTC, Arucard89 commented
I suggest grouping single and range components in one page for each case. This will help reduce the number of menu items in the showcase section. I think it will be more convenient for watching.

2024-06-04 18:50 UTC, amje commented
> I suggest grouping single and range components in one page for each case. This will help reduce the number of menu items in the showcase section. I think it will be more convenient for watching.

Agreed, can we write the stories so we have both single and range slider, but with shared controls.`value` control will be the value for the single slider and `rangeValue` control will be the value for the ranged slider?

2024-06-04 18:51 UTC, amje requested changes

2024-06-04 18:51 UTC, amje commented on playwright/core/types.ts
> +        options?: MountOptions<HooksConfig> & {wrapDivStyles?: React.CSSProperties},
```suggestion
        options?: MountOptions<HooksConfig> & {wrapperStyle?: React.CSSProperties},
```

2024-06-05 14:01 UTC, amje commented
> > > I suggest grouping single and range components in one page for each case. This will help reduce the number of menu items in the showcase section. I think it will be more convenient for watching.
> > 
> > 
> > Agreed, can we write the stories so we have both single and range slider, but with shared controls.`value` control will be the value for the single slider and `rangeValue` control will be the value for the ranged slider?
> 
> @amje, Maybe we could omit the value property altogether? I don't think it is really necessary for the showcases(excluding the default showcase).
> 
> UPD: So my point is to have: -single page for slider(with value prop) -single page for range slider(with value prop) -single and range components in one page for each other special case(without value prop)

@Arucard89  Like this?
`Default` (single default with value)
`Range` (range default with value)
`Size (both single and range without value)`
`Disabled (both single and range without value)`
`// etc`

2024-06-06 08:56 UTC, Arucard89 commented
> @Arucard89 Like this?
> `Default` (single default with value)
> `Range` (range default with value)
> `Size (both single and range without value)`
> `Disabled (both single and range without value)`
> `// etc`

@amje, yes. I believe that it would be helpful for users to play around with the components using the default settings and explore the special, predefined cases.

2024-12-28 18:30 UTC, closed without merging