Feat/user label size
gravity-ui/uikit pull request #1658
Opened 2024-06-17 22:02 UTC by rLukoyanov

2024-06-18 10:40 UTC, amje requested changes

2024-06-18 10:40 UTC, amje commented on src/components/UserLabel/_variables.scss
> +$default-size: map.get($sizes, 'm');
We can refactor styles to use size of `Avatar` component as a basis in layout and not duplicate these heights.

2024-06-18 10:40 UTC, amje commented on src/components/UserLabel/UserLabel.tsx
>  const COMMON_AVATAR_PROPS: Partial<AvatarProps> = {
This constant can be removed

2024-06-18 10:40 UTC, amje commented on src/components/UserLabel/UserLabel.tsx
> +    size: 'm',
Size `"s"` should remain as default in order to keep backward compatibility

2024-06-18 10:40 UTC, amje commented on src/components/UserLabel/README.md
> +| size         | UserLabel size                              |                       `'xs'` `'s'` `'m'` `'l'` `'xl'`                       |    `'m'`     |
`Avatar size`

2024-06-18 18:42 UTC, rLukoyanov commented on src/components/UserLabel/UserLabel.tsx
> +    size: 'm',
Да, но в документации было написано следующее 
<img width="896" alt="Screenshot 2024-06-18 at 22 40 50" src="https://github.com/gravity-ui/uikit/assets/105169805/f91fa23e-5cd1-4199-af7f-53c249de249e">

2024-06-19 10:49 UTC, amje commented on src/components/UserLabel/UserLabel.tsx
> +    size: 'm',
Да, надо это поправить, но отдельным ПРом, и мы включим в следующий мажор его

2024-06-19 11:10 UTC, amje commented
Size `xl` has not round shape:
<img width="176" alt="" src="https://github.com/gravity-ui/uikit/assets/3368839/56730e8d-afb5-45d0-b667-feee41ce30e9">

2024-06-21 19:40 UTC, rLukoyanov commented
<img width="264" alt="Screenshot 2024-06-21 at 23 40 26" src="https://github.com/gravity-ui/uikit/assets/105169805/a7c2ca34-915a-4716-ab11-abf0b3adf069">

2024-06-21 21:09 UTC, DakEnviy approved these changes

2024-06-23 15:25 UTC, amje requested changes

2024-06-23 15:25 UTC, amje commented on src/components/UserLabel/README.md
> +| size         | Avatar size                                 |                       `'xs'` `'s'` `'m'` `'l'` `'xl'`                       |    `'m'`     |
```suggestion
| size         | Avatar size                                 |                       `'xs'` `'s'` `'m'` `'l'` `'xl'`                       |    `'s'`     |
```

2024-06-24 16:27 UTC, amje approved these changes

2024-06-24 16:28 UTC, merged

2024-06-24 16:28 UTC, amje commented
Thanks for contribution!