feat(Avatar): add 2xs Avatar size
gravity-ui/uikit pull request #1721
Opened 2024-07-26 14:43 UTC by PahaN47

2024-07-26 15:00 UTC, amje commented
@PahaN47 Please ensure new size is correctly displayed for Avatar related components: `AvatarStack`, `User`, `UserLabel`

2024-07-31 07:44 UTC, DakEnviy commented
Let's add `2xs` size for `User` component. Also, I believe that 12px font-size would be better in `User` component for sizes `xs` and `2xs`

2024-08-02 13:54 UTC, amje commented on src/components/User/User.scss
> +                @include user-text-small();
Maybe we shouldn't allow `2xs` in User and UserLabel components

2024-08-02 15:56 UTC, DakEnviy commented on src/components/User/User.scss
> +    font-weight: var(--g-text-body-font-weight);
Let's add CSS API for font styles

2024-09-05 11:10 UTC, amje requested changes

2024-09-05 11:10 UTC, amje commented on src/components/User/README.md
> +| `--g-user-small-line-height` | Name line height for `size='xs'` and smaller               |
CSS API is designed to ignore all props, so only 2 vars are relevant: `--g-user-font-size`, `--g-user-line-height`. There should not be CSS API for props variants

2024-09-05 11:10 UTC, amje commented on src/components/User/constants.ts
> +export const DEFAULT_USER_SIZE: UserSize = 'm';
```suggestion
export const DEFAULT_SIZE: UserSize = 'm';
```

2024-09-05 11:10 UTC, amje commented on src/components/User/constants.ts
> +export const NO_DESCRIPTION_SIZES: UserSize[] = ['xs', '2xs'];
```suggestion
export const COMPACT_SIZES: UserSize[] = ['xs', '2xs'];
```

2024-09-12 13:04 UTC, amje approved these changes

2024-09-13 09:35 UTC, DakEnviy approved these changes

2024-09-13 09:43 UTC, merged