feat: add DefinitionList and HelpMark
gravity-ui/uikit pull request #1731
Opened 2024-08-02 13:11 UTC by Raubzeug

2024-10-01 13:12 UTC, amje requested changes

2024-10-10 09:13 UTC, amje requested changes

2024-10-10 09:13 UTC, amje commented on src/components/DefinitionList/index.ts
> +export type {DefinitionListProps, DefinitionListItem} from './types';
DefinitionListItem should be a component, not a type. Let's also reexport `DefinitionListItemProps`

2024-10-10 09:13 UTC, amje commented on src/components/DefinitionList/types.ts
> +export interface DefinitionListItem {
```suggestion
export interface DefinitionListItemProps {
```

2024-10-10 09:13 UTC, amje commented on src/components/DefinitionList/utils.ts
> +export const b = block('definition-list');
Let's move this into `constants.ts`

2024-10-10 09:13 UTC, amje commented on src/components/HelpMark/HelpMark.tsx
> +    delayClosing?: number;
Let's keep it unconfigurable for now

2024-10-10 09:13 UTC, amje commented on src/components/HelpMark/HelpMark.tsx
> +            <button
Can we use Popover's render function children here? That would not add extra element

2024-10-10 09:13 UTC, amje commented on src/components/HelpMark/README.md
> +Component with rendered raw html (use `content` for plain text) and close on mouse leave after timeout set by `delayClosing`:
This description is outdated now

2024-10-10 09:13 UTC, amje commented on src/components/HelpMark/README.md
> +Popover with JSX component as content:
This text is also misleading, while API has changed

2024-10-10 09:13 UTC, amje commented on src/components/HelpMark/__stories__/HelpMark.stories.tsx
> +const DefaultTemplate: StoryFn<HelpMarkProps> = (args) => <HelpMark {...args} />;
Let's write the stories in CSF3 format

2024-10-11 13:12 UTC, Raubzeug commented on CODEOWNERS
> +-   @amje @ValeraS @korvin89
linter did it unexpectedly

2024-10-11 13:35 UTC, Raubzeug commented on src/components/DefinitionList/__stories__/DefinitionList.stories.tsx
> +export default {
I've converted stories to CSF3 format. Lets improve stories content in a separate PR.

2024-10-15 10:34 UTC, amje requested changes

2024-10-15 10:34 UTC, amje commented on src/components/DefinitionList/DefinitionList.tsx
> +            warnOnce('Only <DefinitionList.Item> components is allowed inside <DefinitionList>');
```suggestion
            warnOnce('[DefinitionList] Only <DefinitionList.Item> components is allowed as children');
```

2024-10-15 10:34 UTC, amje commented on src/components/DefinitionList/index.ts
> +export {DefinitionList} from './DefinitionList';
Let's reexport `DefinitionListItem` component as well. There might be issues with dot notation in Next.js applications

2024-10-15 10:34 UTC, amje commented on src/components/HelpMark/README.md
> +| Property    | Type                                            | Required | Default             | Description                                     |
Let's use columns in this order and names: `Name, Description, Type, Default`, no Required column, Type and Default should be center aligned

2024-10-15 11:04 UTC, amje approved these changes

2024-10-15 11:17 UTC, merged