feat(Popup)!: migrate to floating-ui
gravity-ui/uikit pull request #1952
Opened 2024-11-14 18:34 UTC by oynikishin

2024-11-15 16:42 UTC, amje commented on src/components/Popup/README.md
> +`Popup` can be used to display floating content above the page. It is a wrapper around [floating-ui](https://floating-ui.com)
```suggestion
`Popup` can be used to display floating content above the page. It is a wrapper around [Floating UI](https://floating-ui.com)
```

2024-11-15 16:43 UTC, amje commented on src/components/Popup/README.md
> +The `anchorRef` property accepts a ref object of a DOM element.
We will deprecate `anchorRef`, let's remove occurrences in the docs

2024-11-15 16:44 UTC, amje commented on src/components/Popup/types.ts
> +export type PopupAnchorEl = Element | VirtualElement;
Let's name this type fully: `PopupAnchorElement`

2024-11-19 14:12 UTC, amje approved these changes

2024-11-20 06:56 UTC, Raubzeug approved these changes

2024-11-20 12:10 UTC, korvin89 approved these changes

2024-11-20 14:52 UTC, ValeraS requested changes

2024-11-20 15:25 UTC, oynikishin commented on src/components/Popup/Popup.tsx
> +        floatingContext,
As far as I know, we plan to use floating-ui Interactions in high-level components that use Popup

2024-11-22 15:09 UTC, amje commented on src/components/Popup/Popup.tsx
> +        floatingContext,
@ValeraS We will use `useInteractions` in Tooltip, Popover so we need this

2024-11-26 09:44 UTC, oynikishin commented
Add changes to FilePreview because without them the tests would not run locally

2024-11-26 12:35 UTC, ValeraS approved these changes

2024-11-26 14:57 UTC, merged