feat: improve handling aria props
gravity-ui/uikit pull request #1958
Opened 2024-11-21 10:09 UTC by DanisAvko

2024-11-21 11:32 UTC, ValeraS requested changes

2024-11-21 11:32 UTC, ValeraS commented on src/components/ActionsPanel/ActionsPanel.tsx
> +            {...filterDOMProps(otherProps, {labelable: true})}
Aria labelling attributes on element with implicit or explicit  role `none` / `presentation` are redundant. Use appropriate role or remove them.

Please look through other similar places.

2024-11-22 16:56 UTC, ogonkov commented
What is motivation for this changes?

2024-11-22 16:58 UTC, korvin89 commented
> What is motivation for this changes?

@ogonkov https://github.com/gravity-ui/uikit/issues/1929

2024-11-26 16:04 UTC, amje requested changes

2024-12-04 09:20 UTC, ValeraS approved these changes

2024-12-28 13:18 UTC, amje approved these changes

2024-12-28 13:18 UTC, merged