feat(Tabs): allow string for TabItem counter value
gravity-ui/uikit pull request #1989
Opened 2024-12-12 16:17 UTC by EgorKluch

2024-12-12 16:17 UTC, EgorKluch commented on src/components/Tabs/README.md
> -| title    | Tab title                      | `string` `React.ReactNode` |         |
string already includes in ReactNode type

2024-12-12 17:33 UTC, korvin89 requested changes

2024-12-12 17:33 UTC, korvin89 commented on src/components/Tabs/TabsItem.tsx
> +    title: React.ReactNode;
This is html title, it could have only type `string`

2024-12-13 10:13 UTC, korvin89 approved these changes

2024-12-13 10:14 UTC, merged