feat: open modal for the whole page
gravity-ui/uikit pull request #2009
Opened 2024-12-21 17:14 UTC by iapolya

Modal window state stretched to full page, no mardin, no border radius.  Useful on mobile.

2024-12-24 16:55 UTC, amje commented
@iapolya Hi, Modal is not supposed to be open in fullscreen by design. It has no "close" element except its overlay. So it won't be possible to close the Modal on mobile device in such scenario. There is a dedicated component for mobile cases - `Sheet`, which should be used instead

2025-01-28 09:09 UTC, amje requested changes

2025-01-28 09:09 UTC, amje commented on src/components/Modal/Modal.scss
> +        height: var(--g-modal-height, #{$modal-default-height});
Let's apply these styles only for `&__content`:
```
width: var(--g-modal-width, #{$modal-default-width});
height: var(--g-modal-height, #{$modal-default-height});
```

Applying it to all elements could result in unexpected behaviour.

2025-01-31 13:18 UTC, iapolya commented on src/components/Modal/Modal.scss
> +        height: var(--g-modal-height, #{$modal-default-height});
Yes, valid point. This works for the case when I want to use vh, but it's not sufficient when using %.

2025-02-11 16:58 UTC, amje commented on src/components/Modal/Modal.scss
> +        height: var(--g-modal-height, #{$modal-default-height});
content and wrapper represent inner Modal elements, their only purpose it to center the modal, they are not for public tweaking. For the end user they should not be exposed. Why `--g-modal-width` and `--g-modal-height` is not enough?

2025-02-16 18:02 UTC, iapolya commented on src/components/Modal/Modal.scss
> +        height: var(--g-modal-height, #{$modal-default-height});
In the project, we [used 100% for the mobile modal](https://developer.chrome.com/blog/url-bar-resizing?hl=ru), and the styles were like this: 

```
.g-modal__content-aligner {
    height: 100%;
}

.g-modal__content-wrapper,  .g-modal__content {
    height: 100%;
    width: 100%;
}
```

We will switch to [dvh](https://caniuse.com/?search=dvh) in the project. It works correctly on mobile and does not require nested styles. I simplified CSS API

2025-03-18 11:57 UTC, amje approved these changes

2025-03-24 10:51 UTC, merged