feat(Toc): render 6 levels of nested items
gravity-ui/uikit pull request #2010
Opened 2024-12-23 16:07 UTC by sofiushko

2024-12-24 17:22 UTC, amje requested changes

2024-12-24 17:22 UTC, amje commented on src/components/Toc/TocSections/TocSections.tsx
> +export const TocSections = React.forwardRef<HTMLElement, TocSectionsProps>(function Toc(props) {
```suggestion
export const TocSections = React.forwardRef<HTMLElement, TocSectionsProps>(function TocSections(props) {
```

2024-12-24 17:22 UTC, amje commented on src/components/Toc/TocSections/TocSections.tsx
> +const b = block('toc-sections');
```suggestion
const b = block('toc');
```

Let's keep it part of the `toc` block

2024-12-24 17:22 UTC, amje commented on src/components/Toc/TocSections/TocSections.tsx
> +                        onItemClick={onItemClick}
Looks odd to have `onItemClick` in `TocItem` component. Shouldn't it be simply `onClick`?

2024-12-24 17:22 UTC, amje commented on src/components/Toc/TocSections/TocSections.scss
> +#{$block} {
```suggestion
$block: '.#{variables.$ns}toc';

#{$block}__sections {
```

2025-01-09 11:15 UTC, korvin89 commented
@sofiushko Hi! Could you rebase your branch?

2025-01-14 12:10 UTC, sofiushko commented
> @sofiushko Hi! Could you rebase your branch?

done)

2025-01-15 12:42 UTC, amje approved these changes

2025-01-15 15:47 UTC, merged