refactor(Clipboard copy related components): docs and adjustments
gravity-ui/uikit pull request #306
Opened 2022-08-16 04:53 UTC by damask

Added readme
Refactoring

2022-08-16 13:53 UTC, amje commented on src/components/CopyToClipboard/index.ts
> +export * from './types';
This will export some private types from package. `CopyToClipboardStatus ` is the only public here imo.

2022-08-16 13:53 UTC, amje commented on src/components/ClipboardButton/ClipboardButton.tsx
> +export const ClipboardButton: React.FC<ClipboardButtonProps> = ({
What is the point changing function type to `React.FC`?

2022-08-16 13:53 UTC, amje commented on src/components/CopyToClipboard/README.md
> +| timeout  | `Number`   |          | `1000`  | Time in ms to restore initial state (`CopyToClipboardStatus.Pending`)                |
Where this default is set? I can't see in the code.

2022-09-16 08:59 UTC, damask commented
@amje, @ValeraS 
тут что то застряло все, есть еще вопросы?

2022-09-16 14:00 UTC, amje requested changes

2022-09-16 14:00 UTC, amje commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> -export interface CopyToClipboardProps
Why removing `CopyToClipboardProps`?

2022-09-27 14:38 UTC, amje commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> -export interface CopyToClipboardProps
It's not fixed. Please revert this change

2022-10-04 10:44 UTC, damask commented
@amje, @ValeraS could you review once again?

2022-10-04 15:00 UTC, amje requested changes

2022-10-04 15:00 UTC, amje commented on src/components/Label/Label.tsx
> -import {CopyToClipboard, CopyToClipboardStatus} from '../CopyToClipboard';
This change could be reverted now

2022-10-04 15:00 UTC, amje commented on src/components/ShareTooltip/ShareList/ShareList.tsx
> -import {CopyToClipboard, CopyToClipboardStatus} from '../../CopyToClipboard';
This change could be reverted now

2022-10-05 08:56 UTC, amje approved these changes

2022-10-06 14:15 UTC, merged