feat(LayerManager): add focus trapping (#304)
gravity-ui/uikit pull request #307
Opened 2022-08-16 06:32 UTC by Volodomor

2022-08-30 09:55 UTC, ValeraS requested changes

2022-08-30 09:55 UTC, ValeraS commented on src/components/Modal/Modal.tsx
> +        focusTrapOptions,
I guess, these options should depend on `disableEscapeKeyDown`, `disableOutsideClick` props

2022-08-30 09:55 UTC, ValeraS commented on src/components/utils/LayerManager.ts
> +    private focusTraps = new WeakMap<LayerConfig, FocusTrap>();
Do we need to pause/unpause focus trap ourself? From [documentation](https://github.com/focus-trap/focus-trap#one-at-a-time):
> Focus trap manages a queue of traps: if A activates; then B activates, pausing A; then C activates, pausing B; when C then deactivates, B is unpaused; and when B then deactivates, A is unpaused.

2022-08-30 09:55 UTC, ValeraS commented on src/components/Modal/Modal.tsx
> +    focusTrapRef,
I don't think we should give direct access to the `focus-trap` options, we need to use some abstraction here.

2022-08-30 09:55 UTC, ValeraS commented on src/components/Modal/Modal.tsx
> +    focusTrapRef,
When do we need to control focus trap instance outside the component?

2023-02-03 10:57 UTC, amje commented
The feature was implemented in #482 and released in 4.0.0. Closing this PR

2023-02-03 10:57 UTC, closed without merging