test(Button): add button tests
gravity-ui/uikit pull request #327
Opened 2022-09-06 18:03 UTC by niktverd

2022-09-08 10:16 UTC, ogonkov requested changes

2022-09-08 10:16 UTC, ogonkov commented on src/components/Button/__tests__/Button.test.tsx
> +        button.click();
use `userEvent.click` to emulate element click

2022-10-25 17:14 UTC, amje approved these changes

2022-11-07 12:10 UTC, ogonkov approved these changes

2022-11-07 12:19 UTC, merged