feat(Tooltip): add ability to disable display of the tooltip
gravity-ui/uikit pull request #348
Opened 2022-09-29 09:27 UTC by d3m1d0v

In some cases, you may need to forcibly disable the display of the tooltip

2022-09-30 18:41 UTC, amje requested changes

2022-10-03 09:06 UTC, d3m1d0v commented on src/components/Tooltip/Tooltip.tsx
> +    disable?: boolean;
done

2022-10-03 11:41 UTC, amje commented
@d3m1d0v I was thinking about it recently. Are we actually need this prop? We could simply add condition for `open` prop outside component to achieve same result

2022-10-03 12:17 UTC, amje approved these changes

2022-10-03 12:18 UTC, merged