feat: use react-transition in Modal and Popup
gravity-ui/uikit pull request #453
Opened 2023-01-07 20:45 UTC by amje

2023-01-08 17:39 UTC, ValeraS requested changes

2023-01-09 16:21 UTC, amje commented on src/components/Modal/Modal.tsx
> +    const [isMounted, setIsMounted] = React.useState(false);
If CSSTransition and its content are rendered at the same time no transition happen. We explicitly disable transition on first render when open is true

2023-01-09 16:30 UTC, amje commented on src/components/Modal/Modal.tsx
> +                classNames="rt"
Then all classes should be redefined, not just these two. Don't think we want such control. These classes are purely utility

2023-01-09 17:19 UTC, amje commented on src/components/Popup/Popup.scss
>      visibility: hidden;
Popper cant calculate dimensions of `display: none` element when `keepMounted` set to true. Trying to fix this issue...

2023-01-09 18:03 UTC, ValeraS commented on src/components/Modal/Modal.tsx
> +                classNames="rt"
we may to set only used classes.

2023-01-09 18:06 UTC, ValeraS commented on src/components/Modal/Modal.tsx
> +    const [isMounted, setIsMounted] = React.useState(false);
if set `appear` props and for `appear-active` use the same class name like for `enter-active`, it should work.

2023-01-09 19:07 UTC, amje commented on src/components/Modal/Modal.scss
> -    display: none;
move it back

2023-01-09 19:16 UTC, amje commented on src/components/Modal/Modal.tsx
> +    const [isMounted, setIsMounted] = React.useState(false);
Indeed, thanks! Somehow I missed that prop...

2023-01-09 19:25 UTC, amje commented on src/components/Modal/Modal.tsx
> +    const [isMounted, setIsMounted] = React.useState(false);
Did the same for Popup too

2023-01-09 19:26 UTC, amje commented on src/components/Popup/Popup.scss
>      visibility: hidden;
I used negative margins to prevent content blocking instead of `display: none`

2023-01-10 13:25 UTC, ValeraS approved these changes

2023-01-10 13:25 UTC, ValeraS commented on src/components/Modal/Modal.tsx
> +                appear={true}
```suggestion
                appear
```

2023-01-10 13:25 UTC, ValeraS commented on src/components/Popup/Popup.tsx
> +                appear={true}
```suggestion
                appear
```

2023-01-10 21:48 UTC, merged