chore: lint rules
gravity-ui/uikit pull request #467
Opened 2023-01-11 11:21 UTC by ValeraS

2023-04-26 15:20 UTC, amje requested changes

2023-04-26 15:20 UTC, amje commented on .eslintrc
> +                "message": "Please use React.Fragment instead."
There is a dedicated [rule](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md) in eslint-plugin-react

2023-04-26 15:20 UTC, amje commented on tsconfig.json
> +        "importsNotUsedAsValues": "error"
this option was [deprecated](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) in of favor `verbatimModuleSyntax `

2023-05-31 14:13 UTC, korvin89 approved these changes

2023-06-01 08:41 UTC, merged