feat: export LayoutDirection
gravity-ui/uikit pull request #586
Opened 2023-03-28 10:07 UTC by niktverd

2023-03-28 10:23 UTC, amje requested changes

2023-03-28 10:23 UTC, amje commented on src/components/SharePopover/index.ts
> +export {ShareOptions, LayoutDirection} from './constants';
It should be `ShareLayoutDirection`

2023-03-28 12:17 UTC, niktverd commented on src/components/SharePopover/index.ts
> +export {ShareOptions, LayoutDirection} from './constants';
Ok

2023-04-06 15:41 UTC, amje approved these changes

2023-04-06 15:42 UTC, merged