feat(Persona): add `renderButton` prop
gravity-ui/uikit pull request #632
Opened 2023-04-18 17:13 UTC by ogonkov

2023-04-19 10:02 UTC, DaffPunks approved these changes

2023-04-19 10:02 UTC, DaffPunks commented on src/components/PersonaWrap/PersonaWrap.tsx
> +    const closeable = Boolean(onClose || renderButton);
Мне кажется теперь у этой переменной другой смысл. Не `closeable`, а какой-нибудь `withAction`

2023-04-19 10:16 UTC, ogonkov commented on src/components/PersonaWrap/PersonaWrap.tsx
> +    const closeable = Boolean(onClose || renderButton);
It's alvays was like that)

2023-04-19 10:38 UTC, amje requested changes

2023-04-19 10:38 UTC, amje commented on src/components/Persona/Persona.tsx
> +    const renderCloseButton = useCallback(
This button should always be close button. Let's not add a custom renderer here

2024-04-16 16:16 UTC, ogonkov commented
I guess not

2024-04-16 16:16 UTC, closed without merging