feat(Labels): added value prop for "key:value" labels
gravity-ui/uikit pull request #665
Opened 2023-05-16 07:44 UTC by sunduckcow

in this pr
fixed: bad display of icon in 's' size labels
refactored: styles for different sizes
added: support for value prop + story for display all combinations of labels

2023-06-01 10:30 UTC, amje requested changes

2023-06-01 10:33 UTC, amje requested changes

2023-06-01 10:33 UTC, amje commented on src/components/Label/Label.scss
> +                none,
`none` is not valid for `background-color`. Either use `background` property or change `none` to `transparent`

2023-06-07 18:28 UTC, amje requested changes

2023-06-07 18:28 UTC, amje commented on src/components/Label/Label.scss
> +    @if $BorderColor != none {
Why is var name capitalized? It's a typo?

2023-06-09 08:03 UTC, goshander approved these changes

2023-06-09 10:40 UTC, merged