feat(Alert): added new component Alert
gravity-ui/uikit pull request #724
Opened 2023-06-08 14:21 UTC by IsaevAlexandr

Just new component for interface.
Start review from `docs` section in Storybook

related to DATAUI-1590

2023-06-13 17:01 UTC, korvin89 reviewed
Will u add some tests for basic functionality?

2023-06-14 07:51 UTC, IsaevAlexandr commented on src/components/Alert/types.ts
> +    squared?: boolean;
you can change border radius by `className` any time. 

ок, i can change api with squared corners with `pin` api.

I think the best way to work with border radius is `theme` there you can set border radius for all components in one time

2023-06-19 10:07 UTC, korvin89 approved these changes

2023-06-19 12:25 UTC, amje requested changes

2023-06-19 12:25 UTC, amje commented on src/components/Alert/AlertIcon.tsx
> +import type {SVGIconData} from '../Icon/types';
There is type `IconData` in Icon file

2023-06-19 12:25 UTC, amje commented on src/components/Alert/constants.ts
> +export const DEFAULT_ICONS_SIZE = 18;
`_ICON_`, in singular

2023-06-19 12:25 UTC, amje commented on src/components/Alert/types.ts
> +export type AlertTypes = 'normal' | 'info' | 'positive' | 'warning' | 'danger';
`AlertTheme`?

2023-06-19 12:25 UTC, amje commented on src/components/Alert/types.ts
> +    theme?: 'normal' | 'info' | 'positive' | 'warning' | 'danger';
use alias from above

2023-06-19 12:25 UTC, amje commented on src/components/Alert/types.ts
> +    corners?: 'normal' | 'none';
What about different naming? `cornerStyle` with values: `rounded` | `square`

2023-06-19 12:25 UTC, amje commented on src/components/Alert/types.ts
> +    contentCenter?: true;
Maybe `centered: boolean`?

2023-06-19 16:21 UTC, IsaevAlexandr commented
/fixed

2023-06-19 18:08 UTC, amje approved these changes

2023-06-20 10:40 UTC, merged