feat(Card): added accessibility via keyboard
gravity-ui/uikit pull request #771
Opened 2023-06-28 10:27 UTC by KirillDyachkovskiy

UXRFC-155

2023-06-29 08:43 UTC, amje requested changes

2023-06-29 08:43 UTC, amje commented on src/components/Card/Card.scss
> +                box-shadow: 0 0 0 2px var(--yc-color-line-misc);
Let's use pseudo element for outline, box-shadow is conflicting with own shadow

2023-06-29 08:43 UTC, amje commented on src/components/Card/Card.scss
> +            &:focus-within {
Let's use the same technic used in the Button component, mouse click shouldn't trigger outline

2023-06-29 08:51 UTC, ValeraS requested changes

2023-06-29 08:51 UTC, ValeraS commented on src/components/Card/Card.tsx
> +            onKeyDown={handleKeyDown}
Let's use button tag for interactive card to get rid of this handler and eslint errors. And add `role="button"`.

2023-07-04 17:53 UTC, amje requested changes

2023-07-04 17:53 UTC, amje commented on src/components/Card/Card.scss
> +            &:focus-visible {
`:focus-visible` selector is not needed here, we use only for hiding box-shadow

2023-07-04 17:53 UTC, amje commented on src/components/Card/Card.scss
> +                    border: 2px solid var(--yc-color-line-selection-hover);
This chunk of code handles selection hover and should not be affected by focus

2023-07-04 17:53 UTC, amje commented on src/components/Card/Card.scss
> -            border-color: transparent;
Seems like deleted by accident

2023-07-04 17:53 UTC, amje commented on src/components/Card/Card.scss
> +            &:focus-visible {
Same here, no need in this line

2023-07-06 08:25 UTC, amje approved these changes

2023-07-06 09:03 UTC, ogonkov commented on src/components/Card/Card.tsx
> +            case KeyCode.SPACEBAR:
We used to have hook for this, let's restore it like this, and use it instead
```shell
git co 907cadcd2a6750ccfc38f8a2642f954b0b759851 -- src/components/utils/useActionHandlers.ts
```

2023-07-06 09:04 UTC, ogonkov commented on src/components/Card/Card.tsx
> +                    cardRef.current?.click();
why not invoke onClick handler?

2023-07-06 12:40 UTC, amje commented on src/components/Card/Card.tsx
> +                    cardRef.current?.click();
For correct event object I suppose

2023-07-07 14:23 UTC, ValeraS approved these changes

2023-07-07 14:47 UTC, Lunory approved these changes

2023-07-07 14:48 UTC, merged