Feat update button docs
gravity-ui/uikit pull request #800
Opened 2023-07-07 12:29 UTC by sunduckcow

2023-07-11 11:57 UTC, amje requested changes

2023-07-11 11:57 UTC, amje commented on src/components/Button/__stories__/examples/ButtonExampleView/ButtonExampleView.tsx
> +                clear
brick-clear

2023-07-11 11:57 UTC, amje commented on src/components/Button/__stories__/Button.mdx
> +auto - Limits the maximum width of the component, hides overflowing content behind elipses when overflowing
...hides overflowing content by ellipsis.

2023-07-13 07:35 UTC, sunduckcow commented on src/components/Button/__stories__/Button.mdx
>  S – Used when standard buttons are too big (tables, small cards).
What description should XS size have?

2023-07-14 10:42 UTC, amje approved these changes

2023-07-14 10:49 UTC, merged