feat: add className for Pagination component
gravity-ui/uikit pull request #803
Opened 2023-07-07 21:11 UTC by js2me

2023-07-14 11:26 UTC, amje requested changes

2023-07-14 11:26 UTC, amje commented on src/components/Pagination/Pagination.tsx
> +        <div className={b('', {}, className)}>
`b(null, className)`

2023-07-17 09:09 UTC, js2me commented on src/components/Pagination/Pagination.tsx
> +        <div className={b('', {}, className)}>
@amje fixed

2023-08-01 15:31 UTC, jhoncool approved these changes

2023-08-02 10:04 UTC, amje approved these changes

2023-08-02 10:09 UTC, merged