feat(Toc): Toc component added
gravity-ui/uikit pull request #858
Opened 2023-08-02 15:57 UTC by chelentos

2023-09-02 11:52 UTC, amje requested changes

2023-09-02 11:52 UTC, amje commented on src/components/Toc/Toc.scss
> +$block: '.#{variables.$ns}toc';
`$ns` is deprecated. Use `$ns-new` instead

2023-09-02 11:52 UTC, amje commented on src/components/Toc/Toc.scss
> +        font-weight: 500;
Should use one of typography [mixins](https://github.com/gravity-ui/uikit/blob/13ed356b1f8eaf82816f0f6e0ec3f6437b364c41/styles/mixins.scss#L149), font properties can be configured in theme and must not be hardcoded

2023-09-02 11:52 UTC, amje commented on src/components/Toc/TocItem/TocItem.scss
> +$block: '.#{variables.$ns}toc-item';
`$ns-new`

2023-09-02 11:52 UTC, amje commented on src/components/Toc/TocItem/TocItem.tsx
> +                role="radio"
Why `radio`? For a11y would be better to wrap `ul/li` into `nav`

2023-09-02 11:52 UTC, amje commented on src/components/Toc/types.ts
> +    selector?: string;
Can be deleted I guess?

2023-09-02 11:52 UTC, amje commented on src/components/Toc/types.ts
> +    title?: React.ReactNode;
Let's call it `content`?

2023-09-02 11:56 UTC, amje commented
Also I'd use `<a>` in item for better a11y

2023-09-04 11:26 UTC, imechoim commented on src/components/Toc/TocItem/TocItem.tsx
> +    const handleClick = () => onClick(value);
Please, Wrap it in React.useCallback.

2023-09-14 14:08 UTC, amje requested changes

2023-09-14 15:42 UTC, chelentos commented on src/components/Toc/types.ts
> +})[];
Because we only have 2 levels of hierarchy in Toc

2023-09-14 18:44 UTC, amje commented on src/components/Toc/types.ts
> +})[];
It's ok and maybe we'll support any level in the future.

2023-09-15 14:16 UTC, chelentos commented on src/components/Toc/TocItem/TocItem.scss
> +            }
can't use general mixin here because of paddings and component specifics

2023-09-15 14:24 UTC, amje approved these changes

2023-09-15 14:54 UTC, merged