WIP: docs: create readme for Menu
gravity-ui/uikit pull request #930
Opened 2023-08-22 11:11 UTC by NikitaCG

2023-08-23 09:06 UTC, amje requested changes

2023-08-23 09:06 UTC, amje commented on src/components/Menu/README.md
> +| **size**      | Menu size `s - m - l - xl`              |    m    |
This table should have 4 columns: name, description, type, default. No bold in name column, no dashes for empty defaults, types and values wrapped in code

2023-08-23 09:06 UTC, amje commented on src/components/Menu/README.md
> +# Menu.Item
Level 1 header must be only one on a page. Let's describe item and group in main sections

2023-08-23 09:06 UTC, amje commented on src/components/Menu/README.md
> +### Selected
Selected and disabled can be combined into `State` section

2023-08-23 12:52 UTC, NikitaCG commented on src/components/Menu/README.md
> +| **size**      | Menu size `s - m - l - xl`              |    m    |
I was guided on https://github.com/gravity-ui/uikit/tree/main/src/components/Label. It probably needs refactoring.

2023-08-23 13:05 UTC, NikitaCG commented on src/components/Menu/README.md
> +| **size**      | Menu size `s - m - l - xl`              |    m    |
And I see bold in name in `Button` component README too,  where is correct ??

2023-08-23 18:51 UTC, amje commented on src/components/Menu/README.md
> +| **size**      | Menu size `s - m - l - xl`              |    m    |
Label needs refactoring indeed. Bolds in Button are also incorrect, everything else is ok.

2023-08-23 18:52 UTC, NikitaCG commented on src/components/Menu/README.md
> +| **size**      | Menu size `s - m - l - xl`              |    m    |
Ок, I'll fix it

2023-08-23 20:36 UTC, NikitaCG commented on src/components/Menu/README.md
> +| **size**      | Menu size `s - m - l - xl`              |    m    |
done

2023-08-24 09:57 UTC, amje approved these changes

2023-08-24 09:58 UTC, merged