feat(Flex): add alignContent, justifyItems and justifySelf css proper…
gravity-ui/uikit pull request #974
Opened 2023-08-31 11:24 UTC by KirillDyachkovskiy

…ties

2023-08-31 15:12 UTC, IsaevAlexandr approved these changes

2023-08-31 16:24 UTC, amje requested changes

2023-08-31 16:24 UTC, amje commented on src/components/layout/Flex/Flex.tsx
> +    const applyMediaProps = React.useCallback(
No need in useCallback, function is not passed anywhere

2023-08-31 16:24 UTC, amje commented on src/components/layout/Flex/Flex.tsx
> +                alignContent: applyMediaProps(alignContent),
Can we apply this helper for space, gap, and gapRow as well?

2023-09-02 11:59 UTC, amje approved these changes

2023-09-02 12:09 UTC, merged