feat(Table): update README
gravity-ui/uikit pull request #985
Opened 2023-09-04 16:05 UTC by aeksandla

2023-09-04 17:47 UTC, amje requested changes

2023-09-04 17:47 UTC, amje commented on src/components/Table/README.md
> +| getRowId         | Row ID. Used when selecting and sorting rows. If you pass a row, its ID will be the value of the field in the row data named the same as the column ID |                `"string"`
`string` (without quotes)

2023-09-04 17:47 UTC, amje commented on src/components/Table/README.md
> +| theme    | Action disabled |        `"normal"` `"danger"`         | `"normal"`  |
Incorrect description for theme

2023-09-05 10:30 UTC, amje approved these changes

2023-09-05 12:16 UTC, krozhkov approved these changes

2023-09-05 12:22 UTC, merged